export const expensesIcons = [
    {category: 'housing', icon: 'fas fa-home'},
    {category: 'food', icon: 'fas fa-shopping-cart'},
    {category: 'utilities', icon: 'fas fa-lightbulb'},
    {category: 'transportation', icon: 'fas fa-gas-pump'},
    {category: 'clothing', icon: 'fas fa-shopping-bag'},
    {category: 'sports', icon: 'fas fa-dumbbell'},
    {category: 'healthcare', icon: 'fas fa-first-aid'},
    {category: 'entertainment', icon: 'fas fa-glass-martini-alt'},
    {category: 'education', icon: 'fas fa-graduation-cap'},
    {category: 'supplies', icon: 'fas fa-wrench'},
    {category: 'insurance', icon: 'fas fa-car-crash'},
    {category: 'debt', icon: 'fas fa-hand-holding-usd'},
    {category: 'savings', icon: 'fas fa-coins'},
    {category: 'holiday', icon: 'fas fa-plane-departure'},
  ]